---
name: html2dbk
version: 0.03
author:
  - Kathryn Andersen
abstract: Converts an XHTML file into DocBook.
license: perl
requires:
  Cwd: 0
  File::Basename: 0
  File::Spec: 0
  Getopt::ArgvFile: 1.09
  Getopt::Long: 2.34
  HTML::SimpleParse: 0
  Pod::Usage: 0
  XML::LibXML: 0
  XML::LibXSLT: 0
build_requires:
  Test::More: 0
provides:
  HTML::ToDocBook:
    file: lib/HTML/ToDocBook.pm
    version: 0.03
generated_by: Module::Build version 0.2611
